<?php

/**
* Implements hook_mail().
*/
function vbutility_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );

 switch ($key) {
   case 'create_article':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('Article created: @title', array('@title' => $params['node_title']), $options);
     $message['body'][] = $params['message'];
     break;
   case 'form_create':
     $message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = t('Form Created: @title', $options);
     $message['body'][] = $params['message'];
     break;
 }
}

/**
* Implements hook_entity_insert().
*/
function vbutility_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'article')) {
    return;
  }
  $mailManager = \Drupal::service('plugin.manager.mail');
  $module = 'vbutility';
  $key = 'create_article';
  $to = \Drupal::currentUser()->getEmail();
  $params['message'] = $entity->get('body')->value;
  $params['node_title'] = $entity->label();
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = true;
 
  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== true) {
    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent.'), 'error');
  }
  else {
    \Drupal::messenger()->addMessage(t('Emailsend')); 
  }
 
 }

 